### ISSUE TITLE
MangoHUD and VkBasalt activation per process

### ISSUE THREAD

**Issue by dougg0k** [benjamimgois/goverlay#136]
Hi,

For whatever reason, VkBasalt does not get detected by GoOverlay when opening on desktop, what can be done?

Is GoOverlay capable of activating MangoHud or even VkBasalt per process rather than Global? 

Because Global seems to affect some apps on desktop, so, not a very good option to have enabled.

**Comment by benjamimgois** [comment]
Hi @dougg0k , since goverlay complete rewrite i haven't reimplemented vkbasalt yet.  For vkbasalt config you will need to stick to older versions. Right now goverlay only activates Mangohud globally (addint it to /etc/environment). Mangohud has a feature calles "blacklist" where you can specify apps that you don't want it to be used. This feature isn't implemented in goverlay yet, but i might add it to 1.3 release.

**Comment by Milor123** [comment]
> Hi @dougg0k , since goverlay complete rewrite i haven't reimplemented vkbasalt yet. For vkbasalt config you will need to stick to older versions. Right now goverlay only activates Mangohud globally (addint it to /etc/environment). Mangohud has a feature calles "blacklist" where you can specify apps that you don't want it to be used. This feature isn't implemented in goverlay yet, but i might add it to 1.3 release.

Do you think add the support for vkbasalt bro?
I hate configure manually vkbasalt hahaha is very hard UwU

**Comment by benjamimgois** [comment]
What features do you use the most at vkbasalt @Milor123 ? Since i'm not a particular vkbasalt user, i don't know what are the most used ones.

**Comment by Milor123** [comment]
> What features do you use the most at vkbasalt @Milor123 ? Since i'm not a particular vkbasalt user, i don't know what are the most used ones.

Well the main problem with vkbasalt, I guess you already know, is the lack of user-friendliness. Unlike ReShade, vkbasalt doesn't have a user friendly graphical interface, contrary to that, it is probably horrible to use unless you are an expert. What I do in ReShade in 3 minutes, it takes me about 30 minutes to configure in vkbalsalt (if I'm lucky).

![image](https://github.com/user-attachments/assets/9940d927-7ddf-4e46-b75e-54ccf3e5d2d7)

Often you need even the basics


Something that allows you to set color saturation, curves, exposure, temperature, light and shadow management, contrast.

more advanced effect that I consider very useful for certain games, the Eye Adaption (this configures the light/shadows according to the case, the problem is not to put it, is to have something friendly to configure it in the particular case of each game that needs it).

### there is some that I like to use: 
```
Techniques=qUINT_ReGrade@qUINT_regrade.fx,ContrastAdaptiveSharpen@CAS.fx,DELC_Sharpen@qUINT_sharp.fx,EyeAdaption@EyeAdaption.fx,AdaptiveTonemapper@AdaptiveTonemapper.fx
```

My idea of using a vkbasalt is to configure each thing for each game, but to do it in a simple graphical way, and not using a preset that leaves some games wrong.

"Regrade" is a private create by martymcmodding

It would be great if you could create a graphical interface like the ReShade project in windows, but for vkbasalt, because although in linux we can also use it (Refer to ReShade), in many games it breaks, or the anticheat doesn't let us run it, or simply the game only runs well in vulkan and we can't use it.

Maybe an offline graphical interface to start with, that can import the preset files from the ReShade project to make easier the migration there. I understand that there are many limitations because I have tried to use some ReShade libraries in vkbasalt and some of them break or maybe I don't know how to integrate them.

PS: I'm sure the things I mentioned are very basic, maybe other users require more advanced things like MXAO or things related to ray tracing that I don't know if they can be implemented in vkbasalt.
