### ISSUE TITLE
No text in overlay

### ISSUE THREAD

**Issue by TinyBabyOwl** [benjamimgois/goverlay#155]
Goverlay tells me all my dependencies are met and I've got everything turned on, but the overlay window doesn't show text for any of the items I have selected. 

Kernel: 5.14.15-1-MANJARO
DE: Plasma 5.23.2
WM: KWin
CPU: AMD Ryzen 7 3800X (16) @ 3.900GHz 
GPU: NVIDIA GeForce RTX 3080
Drivers: 495.44

**Comment by benjamimgois** [comment]
Hey @TinyBabyOwl , in order to got the text overlay you have to run goverlayt with mangohud using the command:

`mangohud --dlsym ./goverlay --style fusion`

In the latest binary i added a script with the right commands inside the .tar.xz file. Since you're on manjaro, it should work out of the box. How do you installed goverlay ? do got it from the AUR ? or downloaded the binary version ?

**Comment by benjamimgois** [comment]
I'll assume it worked.
