### ISSUE TITLE
Crash on startup, undefined symbol: QLCLOpenGLWidget_override_paintGL

### ISSUE THREAD

**Issue by itsTyrion** [benjamimgois/goverlay#21]
GOverlay used to work, unfortunately idk when it stopped because I rarely open it.

The error is `/usr/libexec/goverlay: symbol lookup error: /usr/libexec/goverlay: undefined symbol: QLCLOpenGLWidget_override_paintG`. Not a lot to work with, but nothing else is printed.

System info: 

- Fedora 36, pretty much every other game-related thing working.   
- GTX 1070, closed nvidia driver, latest version (515.65.01)

I tried reinstalling GOverlay with dnf, removing and reinstalling, downloading the GitHub release (doesn't work, either, just a different error `undefined symbol: QLCLOpenGLWidget_Create`) and even building from source, still errors out. 

The inofficial-ish qt5pas release doesn't change anything, either.
Edit: I reinstalled almost every package with dnf (`sudo dnf reinstall $(rpm -qa|grep -v 100%unrelatedThingsLikeWine)`), no change

**Comment by benjamimgois** [comment]
@itsTyrion  Are you on wayland ?

**Comment by itsTyrion** [comment]
No, Xorg

**Comment by jhu54** [comment]
@benjamimgois  When I had a similar error message, before you lost access to your old github account, I could rollback to an older version of GOverlay. Now, I need to update my qt5pas to the latest 1.2.10 from the davidbannon github (I compile my own GOverlay so installed both the dev and runtime libs). Can you confirm please what version of qt5pas is required for the latest release of GOverlay

**Comment by benjamimgois** [comment]
@jhu54 i always use the latest version on arch repositories, the current version is 2.6.2.2.0-2

https://archlinux.org/packages/community/x86_64/qt5pas/

**Comment by jhu54** [comment]
Thanks - I thought as much. The build date on the arch version is Mar 2, 2022. The version on Fedora rawhide is also 2.6, but is a 2020 build date. Ubuntu/Mint are the same package date. If I use this build, GOverlay fails with the same error OP is reporting because the package manage never gets the latest build (released Mar 1, 2022). Have I misunderstood how the version matching for dependencies works? The source code in 2.10 (what you are seeing as 2.6.2.2.0-2) has significant changes over the repository 2.6 version.
