### ISSUE TITLE
Desktop file validation fails in 0.3.6

### ISSUE THREAD

**Issue by tim77** [benjamimgois/goverlay#46]
Hello. Since `0.3.6` we have this error here:
```
desktop-file-validate /builddir/build/BUILDROOT/goverlay-0.3.6-1.fc33.x86_64/usr/share/applications/goverlay.desktop
/builddir/build/BUILDROOT/goverlay-0.3.6-1.fc33.x86_64/usr/share/applications/goverlay.desktop: error: value "Graphics;Gaming;" for key "Categories" in group "Desktop Entry" contains an unregistered value "Gaming"; values extending the format should start with "X-"
```

**Comment by stephanlachnit** [comment]
Yeah I noticed that as well. IIRC I used "Gaming" because that's what Steam uses, however it is not defined by the freedesktop.org standard (https://specifications.freedesktop.org/menu-spec/latest/apa.html).
At some point I want to contact them and ask to add a "Gaming" category for gaming utilities which are not games (i. e. GOverlay, Steam, Lutris, MangoHud, etc). Until then, one either has to live with the test failing or change it to "Games", the result is the same even though GOverlay isn't a game.

**Comment by tim77** [comment]
Until then maybe we can add `X-` prefix and stick with `X-Gaming`? Now this consider as error, not even warning.

**Comment by stephanlachnit** [comment]
I'm not sure if GOverlay will still be shown in the Games category in Gnome etc then with the `X-` prefix.

Silencing this error doesn't solve the problem. If it's important to you, contact the people who made the standard if they can add a new category. I'm short on time rn.

**Comment by tim77** [comment]
> Yeah I noticed that as well. IIRC I used "Gaming" because that's what Steam uses

Steam have this categories: `Categories=Network;FileTransfer;Game;`

IMO we should stick with `Game`.

**Comment by stephanlachnit** [comment]
> IMO we should stick with `Game`.

It's obviously the wrong category though. The description of the category simply is "A game", which GOverlay most certainly is not. Anyway if it makes you happy send in a PR or ask @benjamimgois to change it. But again, just because the tests aren't failing doesn't mean it's correct.

**Comment by benjamimgois** [comment]
@stephanlachnit even though i agree with you that GOverlay is not game, let's use the "Game" category until we have a Gaming category. I'll make the change on the .desktop file.
