### ISSUE TITLE
Preview button gone?

### ISSUE THREAD

**Issue by LiamDawe** [benjamimgois/goverlay#82]
Unless I am really tired and blind, the preview button to test the layout with glxgears isn't available in the latest version? Gears loads up when the app does now, which is not a particularly nice way to do it.

Can we get the preview button back?

**Comment by benjamimgois** [comment]
@LiamDawe this new release still have some rougth edges. The complete rewrite of Goverlay bigger effort than i predicted. I still plan to bring back Vkbasalt and other features. The integrated 3Dcube was causing all the issues with wayland, that's why i'm using vkcube instead. Hold on for next releases

**Comment by benjamimgois** [comment]
@LiamDawe just make sure you have vkcube installed in your system. It will auto preview your configuration.

![image](https://github.com/user-attachments/assets/51c26577-8243-4772-96d3-2e4bd5164ae0)
