### ISSUE TITLE
Why git clone?

### ISSUE THREAD

**Issue by sabotendarsama** [benjamimgois/goverlay#97]
We have another way do sync with git reshade without cloning this? I have a distro for games and he dont have a git installed so why i have to install git (440mb) to clone only 60mb from reshade git?

Eu gostaria que houvesse uma outra maneira de baixar o reshade sem precisar ter o git instalado em minha distro

**Comment by benjamimgois** [comment]
@sabotendarsama , sorry for my late. I took some days off this month. I'll keep things in english to it can help others with the same problem as you are. Git clone is easiest way for me to synchronize any changes on the repo with all the users. Since you have a distribution, you can just copy all the files in the [repo](https://github.com/benjamimgois/reshade-shaders) to `$HOME/.local/share/reshade`. Just like in this:

![image](https://user-images.githubusercontent.com/7688496/102570954-382bdb80-40c7-11eb-85b7-5caf1af65ab8.png)

This way you don't need to Sync the repo, and all effects will be avaiable when you start Goverlay.

**Comment by benjamimgois** [comment]
Since there's no response i assume it's solved.
